# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41ff4724471d283c942bfddf1c58abb117c19dcb786b99088ef710ffe41c65894ce1eac1f737ef1144dc156716b3ae6c430b8a2631fe58443bb4f49be04a3c35

test:
  secret_key_base: ed4983aa72917f89dfba16f896b2192b2ee2c9ee48e9790ef56a7f2c80d49ee9c7c7c1ec31a4cf199dc4abaeb751795bea3dca7e63ce7a631f1f1b929d0cada6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
